import { INITIAL_IN_LEVEL_GROUP_NODES } from './group-nodes';
import { INITIAL_TUTORIAL_PERMISSION_BOUNDARY_NODES } from './permission-boundary-nodes';
import { INITIAL_IN_LEVEL_POLICY_NODES } from './policy-nodes';
import { INITIAL_TUTORIAL_POLICY_NODES } from './policy-nodes';
import { INITIAL_IN_LEVEL_RESOURCE_NODES, INITIAL_TUTORIAL_RESOURCE_NODES } from './resource-nodes';
import { INITIAL_TUTORIAL_USER_NODES } from './user-nodes';
import { IAMAnyNode } from '@/types';

export const INITIAL_TUTORIAL_NODES: IAMAnyNode[] = [
  ...INITIAL_TUTORIAL_USER_NODES,
  ...INITIAL_TUTORIAL_RESOURCE_NODES,
  ...INITIAL_TUTORIAL_PERMISSION_BOUNDARY_NODES,
  ...INITIAL_TUTORIAL_POLICY_NODES,
];

export const INITIAL_IN_LEVEL_NODES: IAMAnyNode[] = [
  ...INITIAL_IN_LEVEL_RESOURCE_NODES,
  ...INITIAL_IN_LEVEL_POLICY_NODES,
  ...INITIAL_IN_LEVEL_GROUP_NODES,
];
