FROM node:24.13.1-alpine

WORKDIR /app

COPY package.json ./
COPY .yarn .yarn
COPY .yarnrc.yml ./

RUN corepack enable && corepack prepare yarn@4.7.0 --activate

COPY yarn.lock ./
RUN yarn install --immutable

EXPOSE 5173

CMD ["yarn", "dev", "--host", "0.0.0.0"]
