import { FinishEventMapWithDefaults, ObjectiveType } from '@/types/objective-types';

export enum EdgeConnectionFinishEvent {
  COULDTRAIL_SCP_CONNECTED = 'COULDTRAIL_SCP_CONNECTED',
  EC2_REGION_SCP_CONNECTED = 'EC2_REGION_SCP_CONNECTED',
  TRUST_POLICY_ATTACHED_TO_EC2_INSTANCE = 'TRUST_POLICY_ATTACHED_TO_EC2_INSTANCE',
  S3_WRITE_POLICY_ATTACHED_TO_ROLE = 'S3_WRITE_POLICY_ATTACHED_TO_ROLE',
  ACCESS_DELEGATION_POLICY_ATTACHED_TO_USER = 'ACCESS_DELEGATION_POLICY_ATTACHED_TO_USER',
  EC_MANAGEMENT_POLICY_ATTACHED_TO_GROUP1 = 'ELASTICACHE_MANAGEMENT_POLICY_ATTACHED_TO_GROUP1',
  EC_MANAGEMENT_POLICY_ATTACHED_TO_GROUP2 = 'ELASTICACHE_MANAGEMENT_POLICY_ATTACHED_TO_GROUP2',
  EC_MANAGEMENT_POLICY_ATTACHED_TO_GROUP3 = 'ELASTICACHE_MANAGEMENT_POLICY_ATTACHED_TO_GROUP3',
  EC2_LAUNCH_PB_ATTACHED_TO_ROLE = 'EC2_LAUNCH_PB_ATTACHED_TO_ROLE',
}

export enum PolicyCreationFinishEvent {
  ACCESS_DELEGATION_POLICY_CREATED = 'ACCESS_DELEGATION_POLICY_CREATED',
  S3_WRITE_POLICY_CREATED = 'S3_WRITE_POLICY_CREATED',
  ELASTICACHE_MANAGEMENT_POLICY_CREATED = 'ELASTICACHE_MANAGEMENT_POLICY_CREATED',
  EC2_LAUNCH_POLICY_CREATED = 'EC2_LAUNCH_POLICY_CREATED',
}

export enum PermissionBoundaryCreationFinishEvent {
  ROLE_DELEGATION_PB_CREATED = 'ROLE_DELEGATION_PERMISSION_BOUNDARY_CREATED',
}

export enum SCPCreationFinishEvent {
  BLOCK_CLOUDTRAIL_DELETION_SCP_CREATED = 'BLOCK_CLOUDTRAIL_DELETION_SCP_CREATED',
  RESTRICT_EC2_REGION_SCP_CREATED = 'RESTRICTED_EC2_REGION_SCP_CREATED',
  EC2_TRUST_POLICY_CREATED = 'EC2_TRUST_POLICY_CREATED',
}

export enum RoleCreationFinishEvent {
  EC2_ROLE_CREATED = 'EC2_ROLE_CREATED',
}

export type FinishEventMap = FinishEventMapWithDefaults<{
  [ObjectiveType.POLICY_CREATION_OBJECTIVE]: PolicyCreationFinishEvent;
  [ObjectiveType.EDGE_CONNECTION_OBJECTIVE]: EdgeConnectionFinishEvent;
  [ObjectiveType.PERMISSION_BOUNDARY_CREATION_OBJECTIVE]: PermissionBoundaryCreationFinishEvent;
  [ObjectiveType.SCP_CREATION_OBJECTIVE]: SCPCreationFinishEvent;
  [ObjectiveType.ROLE_CREATION_OBJECTIVE]: RoleCreationFinishEvent;
}>;
