import { FinishEventMapWithDefaults, ObjectiveType } from '@/machines/types';

export enum EdgeConnectionFinishEvent {
  TUTORIAL_POLICY_CONNECTED_TO_USER1 = 'TUTORIAL_POLICY_CONNECTED_TO_USER1',
  TUTORIAL_POLICY_CONNECTED_TO_USER2 = 'TUTORIAL_POLICY_CONNECTED_TO_USER2',
  IN_LEVEL_SCP_ATTACHED_TO_OU = 'IN_LEVEL_SCP_ATTACHED_TO_OU',
}

export enum PolicyCreationFinishEvent {
  TUTORIAL_PERMISSION_POLICY_CREATED = 'TUTORIAL_PERMISSION_POLICY_CREATED',
  IN_LEVEL_RESOURCE_BASED_POLICY_CREATED = 'IN_LEVEL_RESOURCE_BASED_POLICY_CREATED',
  IN_LEVEL_IDENTITY_POLICY_CREATED = 'IN_LEVEL_IDENTITY_POLICY_CREATED',
}

export enum SCPCreationFInishEvent {
  TUTORIAL_SCP_CREATED = 'TUTORIAL_SCP_CREATED',
  IN_LEVEL_SCP_CREATED = 'IN_LEVEL_SCP_CREATED',
}

export type FinishEventMap = FinishEventMapWithDefaults<{
  [ObjectiveType.POLICY_CREATION_OBJECTIVE]: PolicyCreationFinishEvent;
  [ObjectiveType.EDGE_CONNECTION_OBJECTIVE]: EdgeConnectionFinishEvent;
  [ObjectiveType.SCP_CREATION_OBJECTIVE]: SCPCreationFInishEvent;
}>;
