export enum LevelObjectiveID {
  ATTACH_TUTORIAL_S3_POLICY = 'ATTACH_TUTORIAL_S3_POLICY',
  CREATE_PERMISSION_BOUNDARY = 'CREATE_PERMISSION_BOUNDARY',
  CREATE_PERMISSIONS_DELEGATION_POLICY = 'CREATE_PERMISSIONS_DELEGATION_POLICY',
}
