export enum LevelObjectiveID {
  ATTACH_TUTORIAL_S3_POLICY = 'ATTACH_TUTORIAL_S3_POLICY',
  ATTACH_POLICY1_TO_GROUPS = 'ATTACH_POLICY1_TO_GROUPS',
  CREATE_MANAGE_RDS_POLICY = 'CREATE_MANAGE_RDS_POLICY',
  ATTACH_POLICY2_TO_GROUPS = 'ATTACH_POLICY2_TO_GROUPS',
}
