import { LevelObjectiveID } from './objective-enums';
import { FinishEventMapWithDefaults, ObjectiveType } from '@/machines/types/objective-types';

export enum RoleCreationFinishEvent {
  TUTORIAL_ROLE_CREATED = 'TUTORIAL_ROLE_CREATED',
  LAMBDA_ROLE_CREATED = 'LAMBDA_READ_ROLE_CREATED',
  EC2_ROLE_CREATED = 'EC2_ROLE_CREATED',
}

export enum TrustPolicyEditFinishEvent {
  TUTORIAL_TRUST_POLICY_EDITED = 'TUTORIAL_TRUST_POLICY_EDITED',
}

export enum EdgeConnectionFinishEvent {
  TUTORIAL_ROLE1_ATTACHED_TO_USER = 'TUTORIAL_ROLE1_ATTACHED_TO_USER',
  TUTORIAL_ROLE2_ATTACHED_TO_USER = 'TUTORIAL_ROLE2_ATTACHED_TO_USER',
  TUTORIAL_POLICY_ATTACHED_TO_ROLE2 = 'TUTORIAL_POLICY_ATTACHED_TO_ROLE2',
  TUTORIAL_USER_ATTACHED_TO_ROLE2 = 'TUTORIAL_USER_ATTACHED_TO_ROLE2',
  S3_READ_POLICY_ATTACHED_TO_LAMBDA_ROLE = 'S3_READ_POLICY_ATTACHED_TO_LAMBDA_ROLE',
  S3_WRITE_POLICY_ATTACHED_TO_EC2_ROLE = 'S3_WRITE_POLICY_ATTACHED_TO_EC2_ROLE',
  LAMBDA_ROLE_ATTACHED_TO_LAMBDA_FUNCTION = 'LAMBDA_ROLE_ATTACHED_TO_LAMBDA_FUNCTION',
  EC2_ROLE_ATTACHED_TO_EC2_INSTANCE = 'EC2_ROLE_ATTACHED_TO_EC2_INSTANCE',
}

export type FinishEventMap = FinishEventMapWithDefaults<{
  [ObjectiveType.EDGE_CONNECTION_OBJECTIVE]: EdgeConnectionFinishEvent;
  [ObjectiveType.ROLE_CREATION_OBJECTIVE]: RoleCreationFinishEvent;
  [ObjectiveType.TRUST_POLICY_EDIT_OBJECTIVE]: TrustPolicyEditFinishEvent;
  [ObjectiveType.LEVEL_OBJECTIVE]: LevelObjectiveID;
}>;
