export enum LevelObjectiveID {
  ATTACH_USER_TO_TUTORIAL_ROLE = 'ATTACH_USER_TO_TUTORIAL_ROLE',
  CREATE_TUTORIAL_ROLE = 'CREATE_TUTORIAL_ROLE',
  GRANT_TUTORIAL_S3_READ_ACCESS = 'GRANT_TUTORIAL_S3_READ_ACCESS',
  GRANT_EC2_S3_WRITE_ACCESS = 'GRANT_EC2_S3_WRITE_ACCESS',
  GRANT_LAMBDA_S3_READ_ACCESS = 'GRANT_LAMBDA_S3_READ_ACCESS',
}
