export enum LevelObjectiveID {
  ALLOW_CREATE_EC2_WITH_TAGS_POLICY = 'ALLOW_CREATE_EC2_WITH_TAGS_POLICY',
  ATTACH_POLICY1_TO_GROUP = 'ATTACH_POLICY1_TO_GROUP',
  CREATE_MANAGE_EC2_POLICY = 'CREATE_MANAGE_EC2_POLICY',
  ATTACH_POLICY2_TO_GROUPS = 'ATTACH_POLICY2_TO_GROUPS',
}
