import { BaseFinishEventMap, ObjectiveType } from '@/machines/types';

export enum LevelObjectiveFinishEvent {
  LEVEL_OBJECTIVE_FINISHED = 'LEVEL_OBJECTIVE_FINISHED',
}

export enum EdgeConnectionFinishEvent {
  S3_READ_WRITE_POLICY_CONNECTED = 'S3_READ_WRITE_POLICY_CONNECTED',
  CLOUDFRONT_READ_POLICY_CONNECTED = 'CLOUDFRONT_READ_POLICY_CONNECTED',
  DYNAMO_DB_READ_WRITE_POLICY_CONNECTED = 'DYNAMO_DB_READ_WRITE_POLICY_CONNECTED',
}

export enum NodeCreationFinishEvent {
  S3_READ_POLICY_CREATED = 'S3_READ_POLICY_CREATED',
  S3_READ_WRITE_POLICY_CREATED = 'S3_READ_WRITE_POLICY_CREATED',
  DYNAMO_DB_READ_WRITE_POLICY_CREATED = 'DYNAMO_DB_READ_WRITE_POLICY_CREATED',
  CLOUDFRONT_DISTRIBUTION_READ_POLICY_CREATED = 'CLOUDFRONT_DISTRIBUTION_READ_POLICY_CREATED',
}

export interface FinishEventMap extends BaseFinishEventMap {
  [ObjectiveType.LEVEL_OBJECTIVE]: LevelObjectiveFinishEvent;
  [ObjectiveType.EDGE_CONNECTION_OBJECTIVE]: EdgeConnectionFinishEvent;
  [ObjectiveType.POLICY_CREATION_OBJECTIVE]: NodeCreationFinishEvent;
  [ObjectiveType.POLICY_EDIT_OBJECTIVE]: never;
  [ObjectiveType.IAM_USER_GROUP_CREATION_OBJECTIVE]: never;
}
