export enum ElementID {
  NewEntityBtn = 'new-entity-btn',
  IAMIdentityNameInput = 'iam-identity-name',
  IAMIdentitySelectorTypeForCreation = 'iam-identity-selector-type-for-creation',
  IAMPolicyRoleSelectorTypeForCreation = 'iam-policy-role-selector-type-for-creation',
  CreateEntitiesMenuItem = 'create-entities-menu-item',
  CreateRolesAndPoliciesMenuItem = 'create-roles-and-policies-menu-item',
  ObjectivesSidePanel = 'objectives-side-panel',
  IAMNodeContentButton = 'iam-node-content-button',
  IAMNodeContentEditButton = 'iam-node-content-edit-button',
  RightSidePanelToggleButton = 'right-side-panel-toggle-button',
  IAMNodeContentCloseButton = 'iam-node-content-close-button',
  CodeEditorPolicyTab = 'code-editor-policy-tab',
  CodeEditorRoleTab = 'code-editor-role-tab',
  CodeEditorSCPTab = 'code-editor-scp-tab',
  CodeEditorHelpButton = 'code-editor-help-button',
  IdentityCreationPopupGroupTab = 'identity-creation-popup-group-tab',
  IdentityCreationPopupUserTab = 'identity-creation-popup-user-tab',
}
