export enum LevelObjectiveID {
  CREATE_TUTORIAL_RESOURCE_BASED_POLICY = 'CREATED_TUTORIAL_RESOURCE_BASED_POLICY',
  CREATE_IN_LEVEL_RESOURCE_BASED_POLICY = 'CREATED_IN_LEVEL_RESOURCE_BASED_POLICY',
  CREATE_IN_LEVEL_IDENTITY_POLICY = 'CREATED_IN_LEVEL_IDENTITY_POLICY',
  ATTACH_IDENTITY_BASED_POLICY_TO_USER = 'ATTACHED_IDENTITY_BASED_POLICY_TO_USER',
}
