export enum LevelObjectiveID {
  ALLOW_CREATE_RDS_WITH_TAGS_POLICY = 'ALLOW_CREATE_RDS_WITH_TAGS_POLICY',
  ATTACH_POLICY1_TO_GROUPS = 'ATTACH_POLICY1_TO_GROUPS',
  CREATE_MANAGE_RDS_POLICY = 'CREATE_MANAGE_RDS_POLICY',
  ATTACH_POLICY2_TO_GROUPS = 'ATTACH_POLICY2_TO_GROUPS',
}
