import { INITIAL_IN_LEVEL_ACCOUNT_NODES } from './account-nodes';
import { INITIAL_IN_LEVEL_OU_NODES } from './ou-nodes';
import { INITIAL_IN_LEVEL_POLICY_NODES } from './policy-nodes';
import { INITIAL_IN_LEVEL_RESOURCE_NODES, INITIAL_TUTORIAL_RESOURCE_NODES } from './resource-nodes';
import { INITIAL_IN_LEVEL_RESOURCE_POLICY_NODES } from './resource-policy-nodes';
import { INITIAL_IN_LEVEL_SCP_NODES } from './scp-nodes';
import { INITIAL_IN_LEVEL_USER_NODES, INITIAL_TUTORIAL_USER_NODES } from './user-nodes';
import { IAMAnyNode } from '@/types';

export const INITIAL_TUTORIAL_NODES: IAMAnyNode[] = [
  ...INITIAL_TUTORIAL_USER_NODES,
  ...INITIAL_TUTORIAL_RESOURCE_NODES,
];

export const INITIAL_IN_LEVEL_NODES: IAMAnyNode[] = [
  ...INITIAL_IN_LEVEL_ACCOUNT_NODES,
  ...INITIAL_IN_LEVEL_OU_NODES,
  ...INITIAL_IN_LEVEL_USER_NODES,
  ...INITIAL_IN_LEVEL_RESOURCE_NODES,
  ...INITIAL_IN_LEVEL_POLICY_NODES,
  ...INITIAL_IN_LEVEL_RESOURCE_POLICY_NODES,
  ...INITIAL_IN_LEVEL_SCP_NODES,
];
