export enum LevelObjectiveID {
  CREATE_DESTINATION_POLICY = 'CREATE_DESTINATION_POLICY',
  CREATE_IAM_USER_ROLE = 'CREATE_IAM_USER_ROLE',
  CREATE_IAM_POLICY_FOR_ASSUMING_ROLE = 'CREATE_IAM_POLICY_FOR_ASSUMING_ROLE',
  GRANT_READ_ACCESS_TO_THIRD_PARTY_USER = 'GRANT_READ_ACCESS_TO_THIRD_PARTY_USER',
}
